### ISSUE TITLE
ctypes.windll is incompatible with Linux and MacOS devices

### ISSUE THREAD

**Issue by ElderFuthark** [aleckjohnson/SeniorDesignWH#1]
`ctypes.windll.user32.MessageBoxW` in `TestScenario3.py` is not OS agnostic. ctypes can be used with other operating systems, but it requires that paths to certain shared libraries be specified. We could use the `platform` Python module to identify the OS in use and then configure ctypes based on that.

Here's the code in question:
```python
ctypes.windll.user32.MessageBoxW(0, "The Estimated Associated cost for "+str(totalNodes)+" Nodes is: Cisco Aironet 1572EAC: $"+str(ciscoCost)+" Ruckus T811-CM: $"+str(ruckusCost),"Estimated Node Cost", 1)
```

**Comment by StarLaGrasse** [comment]
I changed ctypes to tkinter. Please check to see if this fixes the problem
