### ISSUE TITLE
Heatmap generation takes forever to print to screen

### ISSUE THREAD

**Issue by ElderFuthark** [aleckjohnson/SeniorDesignWH#2]
On my machine, painting to the screen takes anywhere from 30 minutes to an hour. I've traced majority of calculation time to be linked to the heatmap generation.
```python
#draw all the nodes in the list
for n in nodeList:
    surf = pygame.Surface(size, pygame.SRCALPHA, 32)
    #pygame.draw.circle(surf, RED, n.getOrigin(), max(int(n.getRad90() * pixPerKM), 1))
    pygame.draw.circle(surf, REDORANGE, n.getOrigin(), max(int(n.getRad80() * pixPerKM), 1))
    pygame.draw.circle(surf, GOLD, n.getOrigin(), max(int(n.getRad70() * pixPerKM), 1))
    pygame.draw.circle(surf, YELLOW, n.getOrigin(), max(int(n.getRad67() * pixPerKM), 1))
    pygame.draw.circle(surf, GREEN, n.getOrigin(), max(int(n.getRad30() * pixPerKM), 1))
    pygame.draw.circle(surf, BLUE, n.getOrigin(), 1)
    surfaces.append(surf)

for surf in surfaces:
screen.blit(surf, [0, 0])
```
For the entire city of Winter Haven, there are a ton of nodes. For each, we're generating five circles. Once each surface is appended, each is drawn on top of the other.
I've tried using convert() on the background image, which was recommended [here](https://stackoverflow.com/questions/48952459/faster-drawing-in-python-pygame), but there was next to no improvement.

**Comment by StarLaGrasse** [comment]
Render time should now be reduced because nodes only spawn on roads

**Comment by StarLaGrasse** [comment]
Also, the off limits areas were being rendered behind the background. I removed that, so render time should have decreased because of that, too

**Comment by ElderFuthark** [comment]
I recreated the behavior of pygame in or script with matplotlib.collecitons. This greatly reduced the drawing time and memory footprint. Please test the modifications found in optimization.py. Let me know if anything needs to be readdressed.
